Repositories/mealorders/config/routes.rb
Rails.application.routes.draw do

	get 'welcome/index'
	resources :meals
	root 'welcome#index'
end

Repositories/mealorders/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Repositories/mealorders/app/models/meal.rb
class Meal < ApplicationRecord
end

Repositories/mealorders/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Repositories/mealorders/app/controllers/meals_controller.rb
class MealsController < ApplicationController
	def new
	end

	def index

	end
	
end

Repositories/mealorders/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Repositories/mealorders/app/helpers/application_helper.rb
module ApplicationHelper
end

Repositories/mealorders/app/helpers/meals_helper.rb
module MealsHelper
end

Repositories/mealorders/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Repositories/mealorders/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mealorders</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Repositories/mealorders/app/views/meals/new.html.erb
<p>new lunch meal</p>

<%= form_for :article, url: meals_path do |f| %>
	<p>
		<%= f.label :number %><br>
		<%= f.text_field :number %>
	</p>
	<p>
		<%= f.label :type %><br>
		<%= f.text_field :type %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

Repositories/mealorders/app/views/welcome/index.html.erb
<p>HEllo world</p>